//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SynergyClone
{
    public partial class PXP2_Login
    {
        protected global::System.Web.UI.WebControls.TextBox username;
        protected global::System.Web.UI.WebControls.TextBox password;
        protected global::System.Web.UI.WebControls.Button btnLogin;
    }
}