//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SynergyClone
{


    public partial class PXP2_Login_Student
    {
    }
}